name: Full reproduction
on: {}
jobs:
  reproduce-all:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: env.yaml
          environment-name: ci
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: install pipelines
        shell: bash -el {0}
        run: |
          pip install -q -e modules/qf_interp_grid_on_track
          pip install -q -e modules/dz_download_ssh_tracks
          pip install -q -e modules/qf_filter_merge_daily_ssh_tracks
          pip install -q -e modules/alongtrack_lambdax
          pip install -q -e modules/dz_alongtrack_mu
          pip install --no-deps -e pipelines/qf_alongtrack_metrics_from_map
      - name: reproduce datachallenge results
        shell: bash -el {0}
        env:
          COPERNICUS_MARINE_SERVICE_USERNAME: ${{secrets.copernicus_login}}
          COPERNICUS_MARINE_SERVICE_PASSWORD: ${{secrets.copernicus_pwd}}
        run: |
          dvc --cd datachallenges/dc_ose_2021 repro -k --pull ${{steps.stages_to_run.outputs.stages}}
      - name: push new files
        shell: bash -l {0}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.aws_key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.aws_secret}}
          AWS_DEFAULT_REGION: ${{secrets.aws_region}}
        run: dvc --cd datachallenges/dc_ose_2021 push -r s3 ${{steps.stages_to_run.outputs.stages}}
      - name: dump metrics report
        if: ${{ (steps.check_author.outputs.skip == 'false') }}
        shell: bash -l {0}
        run: |
          cd datachallenges/dc_ose_2021/data/metrics
          echo 'Data Challenge OSE Gulfstream 2021\n' > ../../report.md
          echo 'Spatial scales resolved $\lambda_x$ \n' >> ../../report.md
          dvc metrics show --md *.json >> ../../report.md
          cat ../../report.md
      - name: Commit changes
        if: ${{ (steps.check_author.outputs.skip == 'false') }}
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update dc_ose_2021 leaderboard'
          add: 'dvc.lock report.md'
          cwd: './datachallenges/dc_ose_2021'
          push: true

