name: Compute metrics
on: [pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: env.yaml
          environment-name: ci
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: install pipelines
        shell: bash -el {0}
        run: |
          pip install -r datachallenges/dc_ose_2021/pipelines.txt
      # - name: make data directories
      #   shell: bash -el {0}
      #   run: |
      #     mkdir -p datachallenges/dc_ose_2021/data/method_outputs
      #     mkdir -p datachallenges/dc_ose_2021/data/prepared
      #     mkdir -p datachallenges/dc_ose_2021/data/metrics
      #     mkdir -p datachallenges/dc_ose_2021/data/downloads
      - name: pull ref
        shell: bash -el {0}
        run: |
          dvc --cd datachallenges/dc_ose_2021 pull --with-deps --allow-missing compute_lambdax
      - name: reproduce datachallenge results
        shell: bash -el {0}
        run: |
          dvc --cd datachallenges/dc_ose_2021 freeze fetch_reference_data
          dvc --cd datachallenges/dc_ose_2021 repro --pull 'compute_lambdax'
          dvc --cd datachallenges/dc_ose_2021 unfreeze fetch_reference_data
      - name: dump metrics report
        shell: bash -l {0}
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'Data Challenge OSE Gulfstream 2021\n' >> ./datachallenges/dc_ose_2021/report.md
          echo 'Spatial scales resolved $\lambda_x$' >> report.md
          dvc metrics show --md datachallenges/dc_ose_2021/data/metrics/lambdax*.json >> ./datachallenges/dc_ose_2021/report.md
          cat report.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update dc_ose_2021 leaderboard'
          add: 'dvc.lock report.md'
          cwd: './datachallenges/dc_ose_2021'
  
